### ISSUE TITLE
Possible injection vulnerability 

### ISSUE THREAD

**Issue by mialahmoka** [ifmeorg/ifme#1006]
# Description 
Upon running an automated scan, Nessus was able to to inject innocuous strings into CGI parameters and read them back in the HTTP response. This doesn't necessarily mean that there is any vulnerability, however it would be worth extended pen testing considering the parameter in question is an authenticity token. For details, see the screenshot.

# Reproduction Steps
Run a Nessus web application scan on www.if-me.org or a localhost application
https://www.tenable.com/downloads/nessus

# Screenshots
![image](https://user-images.githubusercontent.com/43491270/45967174-04de6d00-bfe2-11e8-83a2-16809888afd8.png)

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by sexybiggetje** [comment]
As I understand it:
Seeing from the screenshot this allows to printback data into a piece of javascript; if one is able to submit **"; eval(some js code); var a = "** then it would be an issue but I don't think that's possible there. Or it would be easy to fix to just allow specific chars. The authenticity token probably only needs [a-z0-9]+.

I'm not sure where to check this at the moment since i'm not at home. But at least this is a pointer as to it's severity and it's implication.

**Comment by mialahmoka** [comment]
I believe what it's referring to is you can make a `/user/password?authentication_token=` and insert the authentication token in a POST request and you'll be redirected. I tested this in burp and got redirected to the sign in however it's likely the authentication token was invalid, however I could make a script to test automating this on sign in requests to see if it's an exploit.
![image](https://user-images.githubusercontent.com/43491270/46119974-80971000-c1c2-11e8-8bfe-336f6c877ce7.png)

**Comment by julianguyen** [comment]
@mialahmoka Any updates there?

**Comment by dhuang612** [comment]
I wanna take a look at this
