### ISSUE TITLE
Staging server brainstorm!

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1055]
# Description 

I had a conversation with @baohouse recently about setting up a staging server. This is really helpful for feature work that automated testing may not fully test for.

Given the frequency of commits to this repo, I think having one staging server works for now. But in general, it would be neat to able to spin up staging servers whenever you need them.

I was thinking we could use Github auth to allow contributors who are in the ifmeorg organization to access the staging server.

This is all open to discussion though! Share your thoughts. I personally I don't have experience setting up staging servers that you can spin up whenever (but I've used them plenty lol).

FYI, our production site is hosted on Heroku.

**Comment by tryantwit** [comment]
Since you're using Heroku an option would be to make use of their [Review Apps](https://devcenter.heroku.com/articles/github-integration-review-apps#review-apps-management-and-costs). Each pull request can have its own server quickly spun up then torn down, either manually or automatically.

Another option might be to modify the current git flow to incorporate a `master` `staging` feature branch workflow. Everyone merges into the staging branch and that code is deployed to the staging server for testing then something like once a week or every Tuesday/Thursday you merge staging into master and that code heads to deployment. That creates more of a long term single staging server that everyone feeds into.

**Comment by julianguyen** [comment]
Thanks so much for these insights @tryantwit! I had no idea Review Apps existed, that's awesome.

I think we should move away from deploys whenever something is merged to master. We could also facilitate that with release versions as well.

**Comment by tryantwit** [comment]
Whatever way you go I think moving away from deploys when merged to master is a good way to go. Keep your production environment more insulated from breaking or down time due to an uncaught bug that would have come out in a production like environment.

**Comment by ScotianMan** [comment]
I like Herokus review apps as well. They are great for reviewing individual changes and features, work can then even be pushed to staging where it can play with other merged reviewed work before making its way into the wild. Having a staging/development branch is also a great idea to keep master clean 👍

**Comment by julianguyen** [comment]
Before we tackle the staging problem, we should improve the production deployment process. Just created the referenced issue above ^

@tryantwit @ScotianMan you're welcome to work on it if you're interested! :)

**Comment by julianguyen** [comment]
Gonna close this for now, we should focus on mirroring our dev environment to production.
