### ISSUE TITLE
Should the client app use a type checker?

### ISSUE THREAD

**Issue by alekpentchev** [ifmeorg/ifme#1690]
# Description

ifme client app uses Flow for static type checking. It does its' job but sometimes introduces certain errors like linting errors etc. It forces developers to type their code which creates some overhead on their work. Let's use this thread for discussing the question:

Should the client app use a type checker? Should we stay with Flow or move to TypeScript? Or should we remove type checkers and stay with PropTypes native solution just to check the types of incoming props?

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by alekpentchev** [comment]
In my opinion staying with Flow seems to be the most reasonable solution, because:
- it adds a lot of very useful information to the code (unless not used by the devs),
- raises type errors on-file-save not in the runtime
- it's already used in the client app pretty extensively

For the possible advantages of switching to other solution or withdrawing form type checking at all (but excluding PropTypes) is that we could probably do it incrementally. But for sure it'd require pretty big effort to do it well without putting the app stability at risk.

As I'm more experienced in TypeScript I might be a bit biased towards it :D but let's leave it on the table as one of the possibilities.

**Comment by julianguyen** [comment]
Thanks so much for bringing this up! There's some history as to why we use Flow, but I won't delve into that since it doesn't really matter anymore 😆 

Presently, I have the opinion:
1. If we want static type-checking, we should use TypeScript over Flow. To echo your sentiments, it's more maintained and more people have experience with TS than Flow (including myself haha).
2. If we want to move away from static type-checking but still want to do some basic type-checking, using PropTypes that comes with React works best. 

An open question for us (anyone else feel free to chime in):
* Do we still want static type-checking?

I personally prefer 1) because it gives us a layer of accountability when it comes to the data structures/types we're using. However, 2) would probably require the least amount of time/effort. As an open-source project, we are pretty flexible with deadlines and what we have currently with Flow is working - so there isn't pressure to move to TS or PropTypes.

One pain point though that I've had with TS is using external libraries and resolving missing types. I know libraries like [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) are frequently updated, but still, there's always the possibility that we need to put in more time to create types that are missing from external libraries.

**Comment by alekpentchev** [comment]
@julianguyen thank you for your opinion on that matter. I would also be for option 1. And even if there aren't any types packages for some libraries we're using, we don't have to define them all at once. We can either declare an empty typings module to make TS stop complaining or introduce more and more times step by step.

Nevertheless I can make a small research to check whether libraries we're using have types packages available. :) Then, eventually, I could start with a small POC of how TS could be introduced to this app and if it makes sense, of course.

**Comment by julianguyen** [comment]
I'm leaning towards 1) too.

Sounds good to me @alekpentchev. I think a small POC would work, maybe try on one component or widget first? Let me know if you need help with getting stuff to work with Webpack - I have tons of experience there.

**Comment by alekpentchev** [comment]
Sure, will take a look soon. And that's great! I'd appreciate some tips & tricks when it comes to webpack - JS frameworks made me forget about configuring webpack. 😆So I'll let you know when I'll have some questions.

**Comment by SherSpock** [comment]
@alekpentchev @julianguyen 
Great discussion. I see that after a dialogue that primarily favored the usage of types and seemed to favor replacing Flow with Typescript, this went quiet and then to 'hold off for now'.

Though new to ifme, I also favor typed JavaScript -- I think the added complexity and time to compile are far outweighed by the assurances and readability it brings to a codebase.

Is there anything to be done here at the moment?

**Comment by julianguyen** [comment]
Hey @SherSpock! I think we should move to TypeScript but it's not a pressing thing to do so since Flow does a decent job for now. If you have the bandwidth to get the ball rolling on this, feel free to assign yourself and remove the "hold off for now" label.

**Comment by SherSpock** [comment]
@julianguyen Great! Happy to hear it. There are probably lower-hanging and more sensible fruit for me to go after as a newcomer to the codebase. I'm just excited about this one :)

**Comment by julianguyen** [comment]
I recommended working on the issues that refactor our Rails and React tests :)

**Comment by SherSpock** [comment]
Agreed :)
