### ISSUE TITLE
Suggested Password strength features checks  should be visible to the first time user who are signing up

### ISSUE THREAD

**Issue by developer22-university** [ifmeorg/ifme#1696]
# Description

on looking at the user signup, i discovered it gets very difficult sometime to first-time users while signing up, i discovered this issue, when the user can't set up password correctly for the first time,

PRESENT SITUATION
![Screenshot (105)](https://user-images.githubusercontent.com/51835554/76902488-16948e00-68c2-11ea-9e0f-4dcef09a10f0.png)

 to make sign up simple and easy for mental health community , it is considered to implement suggested password features list visible to all first time users signing up, which verifies all the conditions and approves .This will assist in password strength verification and would be more feasible for everyone. 
WHAT WE WANT:
![Screenshot (106)](https://user-images.githubusercontent.com/51835554/76902572-522f5800-68c2-11ea-8fdb-bc0dab4993aa.png)

Please feel free to reach out for discussions.  Issue Waiting for approval.

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by developer22-university** [comment]
@julianguyen what do you think, is it be useful for community. please send remarks so i can proceed, as i really like to implement this missing feature

**Comment by julianguyen** [comment]
Hey, I think this is a great improvement. Right now those checks are being made on the server-side when the user submits the form. We can do the checks you proposed in the React component. You would want to modify `InputPassword`.

We can discuss the design further too.

**Comment by developer22-university** [comment]
Sure

**Comment by developer22-university** [comment]
julia  going through the code base i need  your help

**Comment by julianguyen** [comment]
I think we should leverage the existing `Tooltip` component to list the information. You find documentation for it [here](http://design.if-me.org/?path=/story/tooltip--element-is-text). We'll want to customize it for this use case of course.

**Comment by kajatiger** [comment]
Hi I also had problems signing up as a first time user. There were 2 problems:
1. After submitting my name, password and email to the form, the error message said that my password requirements didn't match (although they did). The password that I wanted to chose had 1 special character, more than one uppercase, more than one lowercase and more than one digit. Altogether a bit more than 8 characters, but definitely less than 128.
2. When renderering the error message, all my previously entered data was gone, so I would have to type in the name and email again, too. 

<img width="969" alt="Bildschirmfoto 2020-03-24 um 16 57 05" src="https://user-images.githubusercontent.com/15628617/77448410-0cf2b500-6df1-11ea-9ed4-0d23a01fae32.png">

**Comment by julianguyen** [comment]
@kajatiger Yeah that current behaviour could definitely be improved. Right now, we're relying on Rails views (which requires a page refresh or redirect) to display these errors.

We want to catch them earlier on in the React component. The `<InputPassword />` component was just introduced. We'll want to do these password checks in this component.

**Comment by GayathriVenkatesh** [comment]
Hi @developer22-university, since I had worked on the InputPassword component, I had reached out to Julia and she suggested that we collaborate on this issue. Could you please fill me in on your progress, so that we can take it forward?

**Comment by developer22-university** [comment]
If you don't mind I would like to work on this issue, I was busy doing
something , you can look for other issues, thanks

**Comment by developer22-university** [comment]
@GayathriVenkatesh  I  would be happy to collaborate with you in future.

**Comment by GayathriVenkatesh** [comment]
Sure, no problem! :)

**Comment by julianguyen** [comment]
Any updates here?

**Comment by AndresContreras96** [comment]
Hello, is this issue still open? I would like to contribute

**Comment by julianguyen** [comment]
@AndresContreras96 Hey sorry for the late reply feel free to assign yourself.

**Comment by bennpham** [comment]
Hello, I also like to add as first time signing up the site, I also have a tricky time signing up to the site base on the password rules and having to start the form over. 

In regards to password strength meter, I'd recommend [dropbox's `zxcvbn`](https://github.com/dropbox/zxcvbn) library, or you can use  [devise_zxcvbn](https://github.com/bitzesty/devise_zxcvbn) to reject weak passwords on the backend.

--------------------------

On a side note in regards to password rules, I personally wouldn't enforce requiring an uppercase, number, special character, or an upperbound on passwords since for security sake, the best passwords are probably a long sentence/phrase that you can remember, but because the password is long, it makes it harder for machines to brute force the password. 

This XKCD comic summarizes password strengths well. https://xkcd.com/936/

I actually use a password manager for all of my passwords myself (by default I don't always have it set to auto generate a special character and number at all times), but the password is long enough to not be cracked easily, but for master passwords I generally always use a long phrase or sentence. 

-----------------------------

A nice tool I thought that can come in handy if someone wants to utilize [haveIBeenPwned](https://haveibeenpwned.com/) breached passwords API is a gem called [Pwned](https://github.com/philnash/pwned) or [Devise Pwned Password](https://github.com/michaelbanfield/devise-pwned_password) if you use Devise for logins. I don't see as necessary, but I figured it'd be nice to know or reject passwords that had been found in a data breach.

**Comment by julianguyen** [comment]
Hey @bennpham thanks for the really helpful feedback! That library looks interesting and I think it general it would be great to get better and enforcing stronger passwords. I agree that having one uppercase, number, and special character doesn't necessarily yield a secure password.
