### ISSUE TITLE
Update password creation to NIST 2017 standards

### ISSUE THREAD

**Issue by FranceJ** [ifmeorg/ifme#1885]
# Description

The current password creation step has outdated composition requirements It requires a number, special character, upper case, and lower case character The [current NIST standards](https://pages.nist.gov/800-63-3/sp800-63b.html#app) specifically call out these kinds of restrictions as commonly resulting in less secure user passwords

The password field should composition rules should be updated to be in line with the new recommendations Specifically, the composition requirements should be removed and the minimum character requirement should remain.

The NIST document contains other recommendations for improving the password system, such as checking against known leaked sources, providing a password strength meter to help users choose strong passwords, and checking against common passwords and providing advice (not restrictions) based on the results. These could also be implemented but likely add too much scope to the simple change of removing the complexity restrictions, which is a simple change which adds value.

**Comment by bennpham** [comment]
I'll probably like to take this on sometime around Friday :) . I remember posting about this on the **Suggested Password Strength Features** issue thread in regards to password strength meter and XKCD comic summary on password strengths: https://github.com/ifmeorg/ifme/issues/1696#issuecomment-678841098

I think the [Devise Pwned Password](https://github.com/michaelbanfield/devise-pwned_password) gem would be nice to utilize [haveIBeenPwned](https://haveibeenpwned.com/) breached passwords API to check for known leaked sources.

XKCD comic in regards to passwords: https://xkcd.com/936/

Here's another article (which is about 3 years old by now since its in 2017) that offer some nice hints on password policies: https://medium.com/@securitystreak/password-policy-template-2017-best-practices-cbdcbb6beb49

For this issue, I'd probably like to try to implement the following:

- the Devise Pwned Password gem to prevent known hacked passwords
- remove the extra password requirements
- set minimum password to around 8 characters (NIST recommendation although [this article](https://medium.com/@securitystreak/password-policy-template-2017-best-practices-cbdcbb6beb49) prefers at least 16 to enforce long passwords)

Not sure if I'd go beyond scope, but you can also change some Devise settings to lock out an account after 10 failed login attempts or show CAPTCHA after 3 failed attempt. Maybe a log of some sort for login attempts (Rails have paper trails gem or something for logs).

**Comment by bennpham** [comment]
Taken from NIST itself 

> Clearly communicate information on how to create and change memorized secrets.
> Clearly communicate memorized secret requirements, as specified in Section 5.1.1.
> Allow at least 64 characters in length to support the use of passphrases. Encourage users to make memorized secrets as lengthy as they want, using any characters they like (including spaces), thus aiding memorization.
> Do not impose other composition rules (e.g. mixtures of different character types) on memorized secrets.
> Do not require that memorized secrets be changed arbitrarily (e.g., periodically) unless there is a user request or evidence of authenticator compromise. (See Section 5.1.1 for additional information).

I am going to drop the `password_histories` table as well. Not allowing old passwords by storing a password history is actually less secure. We should only force a change of password if the password is confirmed to be compromised. 

You can listen to [Lance Spitzner talk](https://youtu.be/UWmGm-lu-5g?t=1800) or read his [blog from SANS](https://www.sans.org/security-awareness-training/blog/time-password-expiration-die) in regards to it. As a matter of fact, having password histories make it easier for attackers to try and crack your password because instead of having just 1 password to crack, attackers will now have multiple passwords to crack. They just need at least 1 out of all the histories to crack vs 1 out of 1. 

From a user standpoint, if I were to have to make a new password every time, not write it down on paper, have a bunch of symbols and characters in the password and all of a sudden, my password expires. The easiest way for me to remember that password is simply append 1, 2, 3, 4, 5 to that. 

That'd make it easier for machines to break and harder for users to remember.
