### ISSUE TITLE
Groups Link Possible Bug

### ISSUE THREAD

**Issue by Kyliec89** [ifmeorg/ifme#1991]
# Description

When accessing the Groups page within the application, there is a bolded blue "Group" within the text, but when clicking it, it does not seem to respond. I understand that if you are not part of any groups, there is nothing on that page to navigate to, and my account is not a member of any groups. I am not sure if this function looks different for someone who is a part of a group, and maybe that is the issue. The similarly bold word "Meetings" in that paragraph also makes it look clickable, but it isn't, so it is a little confusing. If the clickable "Groups" isn't intended to navigate to anything different, it might be clearer to change it so it isn't clickable either. 

# Reproduction Steps

Sign in, and then navigate to the Groups page, and click the word "Groups" within the first paragraph. As I mentioned in the description, my account is not a member of any groups, so that may be a factor. The same issue occurs on Safari and Google Chrome on a macOS Catalina 10.5.4. 

# Screenshots
---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by julianguyen** [comment]
Hey @Kyliec89 thanks for reporting this! Yeah, this is definitely a bug and not so great experience. The reason why there are links is because the text is also being use don our [FAQ page](https://www.if-me.org/faq). I think we want to solve this by removing the links on the other pages this text appears in.

Namely, in https://github.com/ifmeorg/ifme/blob/caed206940196e645ca9a16a4919c3b399a4fc42/app/views/groups/index.html.erb#L45, just pass in `t('groups.singular')` instead of `link_to()`.

Would you be interested in fixing this?
