### ISSUE TITLE
Add to the mental health resources page!

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#486]
We have a [page](http://if-me.org/resources) on our site with mental health resources categorized under communities, education, hotlines, and services with relevant tags.

Post your favourite resources here. Feel free to make a pull request with yours, be sure include internationalization for the tags. Please use our #i18n channel on Slack to ask for translations!

**Comment by shelleyvadams** [comment]
Still getting my bearings here, but I have years of bookmarks -- https://www.bibsonomy.org/user/shelley.adams/mentalhealth -- gleaning welcome.

**Comment by julianguyen** [comment]
Wow, this is amazing, thank so much for sharing @shelleyvadams! <3 <3 <3
 Let's definitely add this!

**Comment by Caro-Lin** [comment]
Dear all,

I'm totally new to the open source community and just tried to make my first pull-request by adding some entries to the resources page. I also created a list of books, videos, talks, all mental health related that might be helpful but doesn't really fit the criteria for the existing categories Education, Communities and Hotlines. Feel free to use it [gist-list](https://gist.github.com/Caro-Lin/6755faa435bfe488924d0e10650423da).

**Comment by andy5995** [comment]
Is this a resource you'd like added?

[Canvas of the Minds](https://acanvasoftheminds.com/)

**Comment by andy5995** [comment]
I'm adding more resources and will wait a few days to submit the PR. If anyone wants to suggest a resource, I'll add it.

**Comment by andy5995** [comment]
I'd like to add some more music therapy resources @deejayres . I saw some mentioned in [your article](https://medium.com/ifme/13-songs-to-reduce-anxiety-stress-58eb9b362867); any other suggestions?

**Comment by desirottman** [comment]
@andy5995 in my last blog post I mentioned https://www.looplabs.com/beta and https://www.ambient-mixer.com/ as places online that people with no musical experience could create tracks.. i'm digging around for more!

**Comment by desirottman** [comment]
http://musictherapyactivities.wikia.com/wiki/Music_Therapy_Activities_Wiki

**Comment by andy5995** [comment]
@desirottman Since you're interested in getting experience with git, I decided to submit my existing changes, so you can do a separate PR with some of your music therapy resources (and other resources you might think of) :) Let me know if you have any questions

**Comment by sexybiggetje** [comment]
For the upcoming Dutch locale ('nl') one could add the following:

- http://www.depressievereniging.nl/ - Semi state organisation with information and research on depression and related mental ilnesses. Provides experience stories and lobbies for research. Organises support groups.
- https://www.113.nl/ - Suicide prevention hotline (phone, chat), information, training for volunteers
- https://mindblue.nl/ - Community, semi curated, for stories and experiences and general education about mental illness
- https://www.indigo.nl - Nationwide support institute for all mental health problems. Provides information and places for help.
- http://labyrint-in-perspectief.nl/ - Support for loved ones of people with mental health issues, provides opportunities for meetings with people in similar conditions.

Note, all these resources are in Dutch, but contact options usually can be English as well because of the high English proficiency in the Netherlands. But best mark them as Dutch.

**Comment by maribelduran** [comment]
I just created a pull request for ✨  [Insight Timer](https://insighttimer.com/) ✨

Insight Timer is a **free** meditation app that includes guided meditations that range from recovery, acceptance, gratitude, sleep, depression, emotional balance, mindfulness, and the list goes on! They are taught by the best meditation teachers around the world and the community is so supportive. Just wanted to share this here too 😊
