### ISSUE TITLE
Admin: Report dashboard

### ISSUE THREAD

**Issue by stebbins** [ifmeorg/ifme#861]
Part of #811
Report dashboard
- View reports
- Take action on reports (ignore, message reporter, message poster, delete post, ban poster)
- History of past reports by user

**Comment by camillevilla** [comment]
More info from the original ticket:
- Any “admin” user and can go in and open a panel and block users
  - Admin users also see the emails of the users, so that they can email them for any follow-up
  - Make the link to this dashboard obvious in the header. I suggest maybe a smaller header above the current one that appears just for admin users
  - Also add notification badge to the header link if new reports are pending (may split this off to another ticket)
