### ISSUE TITLE
Report model

### ISSUE THREAD

**Issue by stebbins** [ifmeorg/ifme#863]
What should the report model look like?

My first thought:
```
reports
-----
INT  reporter_id
INT  reportee_id
INT  status
INT  comment_id (optional)
STR  note (optional)
DATE created_at
DATE updated_at
```

**Comment by stebbins** [comment]
@alvarocasadoc thoughts?

**Comment by alvarocasadoc** [comment]
I think that's a good design. Maybe we could keep the comment_id also optional for letting users report others from their profiles (just in case the reportee deleted the comment or any other problem happens). 

Also, I think maybe `comment` will do well to avoid repeating "report" when accessing the field (i.e: `@report.comment` vs `@report.report_comment`)

**Comment by stebbins** [comment]
Agreed, that sounds good. I'll update the OP's layout.

**Comment by alvarocasadoc** [comment]
Yes! I think that will work well. We could also add an integer field named "state" to handle (pending, active, archived, solved) instead of a"read" column if we want to handle more statuses. 

We could even create a new database table `Status` where we can save all the different status codes such as "active", "archived", etc. and replace that `read` or `status` field for a reference to this table. I think this approach will be more scalable. What do you think?

**Comment by stebbins** [comment]
Excellent, I agree & will implement.

**Comment by stebbins** [comment]
Hi @alvarocasadoc,
I came across some practical issues when implementing a `Status` table:
1. The data in `Status` and the meaning of `status_id` in `Report` is opaque and could cause understanding issues for future devs
2. The data in `Status` doesn't persist and needs to be manually entered in each environment (this came up in testing)
3. The data in `Status` seems awkwardly removed from `Report`. Some of this can be worked around but not very elegantly 

Instead, I propose declaring an [enum attribute](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html) on `Report`. Then, we can create a hash of report statuses directly in the model while still retaining flexibility and scalability. I think this solves all the above problems:
1. The status is explicitly defined in `Report`
2. The status is permanently stored at the model level instead of as rows in the db
3. The status definitions are directly in the `Report` model in plain text

What do you think?

**Comment by stebbins** [comment]
I'm also going to rename `comment` to `note` in `Report` in order to avoid collisions when joining `Comment`

**Comment by alvarocasadoc** [comment]
I think the enum approach is really clever! Also, renaming comment to note is a great decission 👍 I'll check the project out this weekend because I'm really busy at college and I'll keep you updated. Great work!!!

**Comment by alvarocasadoc** [comment]
I've been wondering about how are we going to translate all status messages. 

I thought before of the `ReportStatus` database table because it could have a column for each language, but this would mean to leave enum approach aside. 

I also think we could stick with the `integer` field and convert it with a helper method into text so the only data stored in the database is a number and the text is all coded in the translation files. 

I didn't came across with any way to keep the enum approach and translate the text effectively. Do you have any idea? :thinking:

**Comment by stebbins** [comment]
Great point! I think one of the advantages of enum is that the data stored is already an integer, so I think that the helper method to convert it into text could absolutely be an effective way to provide internationalization. We could also loop in Julia or someone else to give another perspective on it - I'm sure concerns like this have been brought up before on the project, since it's already fairly well internationalized!

**Comment by timorthi** [comment]
The [Rails i18n documentation](http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models) has some good examples for this. Based on the docs and [this example](https://stackoverflow.com/a/30361971/3321836), it looks like something like the following will work:
```
# report.rb
class Report < ActiveRecord::Base
  enum status: %i[active archived]
end
```
```
# en.yml
en:  
  activerecord:   
    attributes:      
      report/status:        
        active: "Active"        
        archived: "Archived"
```
To get the translation:
```
Report.human_attribute_name("status.#{@report.status}")
```

**Comment by stebbins** [comment]
@timorthi That looks great - thanks for the input! 

@alvarocasadoc Will the above solution work for you? I think it would be wise especially because it will stay consistent with ifme's existing i18n support.

**Comment by alvarocasadoc** [comment]
Yes!!! I think @timorthi's advice is really the way we should go!

**Comment by camillevilla** [comment]
Thanks again for looking into this @stebbins! @aSquare14 and @prateksha have picked this up for Rails Girls Summer of Code. We're currently working on this in #870.
