### ISSUE TITLE
Reports: writing a notification email for banned users

### ISSUE THREAD

**Issue by alvarocasadoc** [ifmeorg/ifme#873]
We are currently working on the reporting users feature and we are sending an email to the reported user. Right now I've written this message:

"Your account has been suspended due to behaviour not allowed in our Terms and Conditions. We are currently revising your case and will keep you updated."

I think we should link "Terms and Conditions" to the doc page and we could also give users a way to contact us if they think the ban was an error. Any other ideas and suggestions are welcome!

**Comment by 9jaswag** [comment]
Hi @alvarocasadoc. I'd like to work on this issue

**Comment by Transvivor** [comment]
Something to add to this. It might be nice for the user to have a chance to see the rules when they are first signing up or to have them visually available and simplified somewhere. 

As for the email: 

We at if me, value the safety of the community in which all users can share their stories safely. We noticed activity on your account that does not align with our Terms & Conditions. Due to this your account is under suspension. Remember if there are multiple warnings your account will be banned. 

If you believe that this was a mistake please reach out to our support team at example@ifme.com

Kindly, 
The Team At if me

**Comment by alvarocasadoc** [comment]
Definitely that's a good idea. We should add the rules on the sign up page. I'm adding that to issue #902 right now.
